# Generated by Django 5.0.7 on 2024-08-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
