# Generated by Django 5.0.7 on 2024-08-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
    ]
