# Generated by Django 5.0.7 on 2024-08-14 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_auto_20240814_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='usuario',
        ),
    ]
