# Generated by Django 5.0.7 on 2024-08-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_remove_tarea_completada'),
        ('tareas', '0002_tarea_completada_alter_tarea_id'),
    ]

    operations = [
    ]
