# Generated by Django 5.0.7 on 2024-08-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_merge_20240809_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
    ]
