# Generated by Django 5.0.7 on 2024-08-14 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_remove_tarea_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='tareas.usuario'),
            preserve_default=False,
        ),
    ]
